/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
import type * as systemContracts from "./system-contracts";
export type { contracts };
export type { systemContracts };
