/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxySol from "./Proxy.sol";
export type { AccountFactory } from "./AccountFactory";
export type { ArgentAccount } from "./ArgentAccount";
export type { TestDapp } from "./TestDapp";
export type { proxySol };
