/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  IL2Messenger,
  IL2MessengerInterface,
} from "../../../../../../@matterlabs/zksync-contracts/l2/contracts/L2ContractHelper.sol/IL2Messenger";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_message",
        type: "bytes",
      },
    ],
    name: "sendToL1",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IL2Messenger__factory {
  static readonly abi = _abi;
  static createInterface(): IL2MessengerInterface {
    return new utils.Interface(_abi) as IL2MessengerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL2Messenger {
    return new Contract(address, _abi, signerOrProvider) as IL2Messenger;
  }
}
